name: Build Front

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: build-front-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend/wmiTool-client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Angular project
        run: npx ng build --base-href /gazawayj-wmitool/

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/wmiTool-client/dist/wmiTool-client/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4